import { Car, CarCategory, ComparisonPoint } from './types';

export const FLEET_DATA: Car[] = [
  {
    id: '1',
    name: 'Tesla Model Y Performance',
    category: CarCategory.ELECTRIC,
    pricePerDay: 135,
    image: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80',
    specs: {
      seats: 5,
      transmission: 'Automatik',
      fuel: 'Elektro',
      range: 514,
      power: 534,
    },
    features: ['Autopilot', 'Viel Stauraum', 'Supercharging inkl.'],
    isAvailable: true,
  },
  {
    id: '2',
    name: 'BMW 5er Touring M-Sport',
    category: CarCategory.BUSINESS,
    pricePerDay: 160,
    image: 'https://images.unsplash.com/photo-1658327915598-a28d54d5885e?auto=format&fit=crop&w=800&q=80',
    specs: {
      seats: 5,
      transmission: 'Automatik',
      fuel: 'Diesel',
      power: 286,
    },
    features: ['Business Paket', 'Head-Up Display', ' xDrive'],
    isAvailable: true,
  },
  {
    id: '3',
    name: 'Audi Q8 e-tron',
    category: CarCategory.SUV,
    pricePerDay: 195,
    image: 'https://images.unsplash.com/photo-1614026480209-cd9c3d59027e?auto=format&fit=crop&w=800&q=80',
    specs: {
      seats: 5,
      transmission: 'Automatik',
      fuel: 'Elektro',
      range: 582,
      power: 408,
    },
    features: ['Luftfederung', 'Virtual Cockpit', 'Matrix LED'],
    isAvailable: true,
  },
  {
    id: '4',
    name: 'Porsche Macan S',
    category: CarCategory.SPORT,
    pricePerDay: 220,
    image: 'https://images.unsplash.com/photo-1503376763036-066120622c74?auto=format&fit=crop&w=800&q=80',
    specs: {
      seats: 5,
      transmission: 'Automatik',
      fuel: 'Benzin',
      power: 380,
    },
    features: ['Sport Chrono', 'BOSE Sound', 'Allrad'],
    isAvailable: true,
  },
  {
    id: '5',
    name: 'Mercedes-Benz EQE',
    category: CarCategory.BUSINESS,
    pricePerDay: 180,
    image: 'https://images.unsplash.com/photo-1678732626325-1e42100863dc?auto=format&fit=crop&w=800&q=80',
    specs: {
      seats: 5,
      transmission: 'Automatik',
      fuel: 'Elektro',
      range: 645,
      power: 292,
    },
    features: ['Hyperscreen', 'Fahrassistenz Plus', 'Digital Light'],
    isAvailable: false,
  },
  {
    id: '6',
    name: 'VW Multivan T7 Hybrid',
    category: CarCategory.SUV,
    pricePerDay: 150,
    image: 'https://images.unsplash.com/photo-1669651581423-a267e157291a?auto=format&fit=crop&w=800&q=80',
    specs: {
      seats: 7,
      transmission: 'Automatik',
      fuel: 'Hybrid',
      power: 218,
    },
    features: ['7 Sitze', 'Panoramadach', 'Konferenztisch'],
    isAvailable: true,
  },
];

export const COMPARISONS: ComparisonPoint[] = [
  { feature: 'Modell-Garantie', us: 'Exakt das gebuchte Auto', others: '"Oder ähnlich" (Lotterie)' },
  { feature: 'LSZG Airport Service', us: 'Übergabe am Rollfeld', others: 'Nicht verfügbar / Taxi nötig' },
  { feature: 'Versicherung', us: 'All-Inclusive (0.- SB)', others: 'Hohe Selbstbehalte' },
  { feature: 'Check-In', us: 'Digital vor Ankunft', others: 'Warten am Schalter' },
  { feature: 'Versteckte Kosten', us: 'Keine', others: 'Tankregelungen, Gebühren' },
];